/*
 * This file is generated by jOOQ.
 */
package vc.live.dto;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Deaths implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final String deathMessage;
    private final String victimPlayerName;
    private final UUID victimPlayerUuid;
    private final String killerPlayerName;
    private final UUID killerPlayerUuid;
    private final String weaponName;
    private final String killerMob;

    public Deaths(Deaths value) {
        this.time = value.time;
        this.deathMessage = value.deathMessage;
        this.victimPlayerName = value.victimPlayerName;
        this.victimPlayerUuid = value.victimPlayerUuid;
        this.killerPlayerName = value.killerPlayerName;
        this.killerPlayerUuid = value.killerPlayerUuid;
        this.weaponName = value.weaponName;
        this.killerMob = value.killerMob;
    }

    @JsonCreator
    public Deaths(
            @JsonProperty("time") OffsetDateTime time,
            @JsonProperty("deathMessage") String deathMessage,
            @JsonProperty("victimPlayerName") String victimPlayerName,
            @JsonProperty("victimPlayerUuid") UUID victimPlayerUuid,
            @JsonProperty("killerPlayerName") String killerPlayerName,
            @JsonProperty("killerPlayerUuid") UUID killerPlayerUuid,
            @JsonProperty("weaponName") String weaponName,
            @JsonProperty("killerMob") String killerMob
    ) {
        this.time = time;
        this.deathMessage = deathMessage;
        this.victimPlayerName = victimPlayerName;
        this.victimPlayerUuid = victimPlayerUuid;
        this.killerPlayerName = killerPlayerName;
        this.killerPlayerUuid = killerPlayerUuid;
        this.weaponName = weaponName;
        this.killerMob = killerMob;
    }

    /**
     * Getter for <code>public.deaths.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.deaths.death_message</code>.
     */
    public String getDeathMessage() {
        return this.deathMessage;
    }

    /**
     * Getter for <code>public.deaths.victim_player_name</code>.
     */
    public String getVictimPlayerName() {
        return this.victimPlayerName;
    }

    /**
     * Getter for <code>public.deaths.victim_player_uuid</code>.
     */
    public UUID getVictimPlayerUuid() {
        return this.victimPlayerUuid;
    }

    /**
     * Getter for <code>public.deaths.killer_player_name</code>.
     */
    public String getKillerPlayerName() {
        return this.killerPlayerName;
    }

    /**
     * Getter for <code>public.deaths.killer_player_uuid</code>.
     */
    public UUID getKillerPlayerUuid() {
        return this.killerPlayerUuid;
    }

    /**
     * Getter for <code>public.deaths.weapon_name</code>.
     */
    public String getWeaponName() {
        return this.weaponName;
    }

    /**
     * Getter for <code>public.deaths.killer_mob</code>.
     */
    public String getKillerMob() {
        return this.killerMob;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Deaths (");

        sb.append(time);
        sb.append(", ").append(deathMessage);
        sb.append(", ").append(victimPlayerName);
        sb.append(", ").append(victimPlayerUuid);
        sb.append(", ").append(killerPlayerName);
        sb.append(", ").append(killerPlayerUuid);
        sb.append(", ").append(weaponName);
        sb.append(", ").append(killerMob);

        sb.append(")");
        return sb.toString();
    }
}
