/*
 * This file is generated by jOOQ.
 */
package vc.live.dto.enums;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum Connectiontype {

    JOIN("JOIN"),

    LEAVE("LEAVE");

    private final String literal;

    private Connectiontype(String literal) {
        this.literal = literal;
    }
}
