name: 2b2t.vc-discord Build

on:
  pull_request:
  push:
    branches:
      - "mainline"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Elevate wrapper permissions
        run: chmod +x ./mvnw

      - name: Build 2b2t.vc-discord
        run: ./mvnw install spring-boot:repackage

      - name: Upload Java Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2b2t.vc-discord
          path: target/2b2t.vc-discord-*.jar
